import {defineConfig} from "vite";
import vue from '@vitejs/plugin-vue';
import path from "path";
import UnoCSS from 'unocss/vite'
import AutoImport from 'unplugin-auto-import/vite';
export default defineConfig({
    plugins: [
        vue(),
        UnoCSS(),
        AutoImport({
            imports: ['vue'],
            dts: 'src/typings/auto-imports.d.ts',
            vueTemplate: true,
        })
    ], // to process SFC
    resolve: {
        alias: {
            '@': path.resolve(__dirname, '.', './src/'),
        },
    },
    build: {
        lib: {
            entry: path.resolve(__dirname, 'index.ts'),
            name: "{{repo_name}}",
            formats: ['es', 'umd'], // adding 'umd' requires globals set to every external module
            fileName: (format) => `{{repo_name}}.${format}.js`,
        },
        rollupOptions: {
            // 预依赖(peerDependencies)的模块不要打包到库中
            external: ['vue', /primevue\/.+/], // not every external has a global
            output: {
                // disable warning on src/index.ts using both default and named export
                exports: 'named',
                // Provide global variables to use in the UMD build
                // for externalized deps (not useful if 'umd' is not in lib.formats)
                globals: {
                    vue: 'Vue',
                },
            },
        },
        emptyOutDir: false, // to retain the types folder generated by tsc
    },
});
